INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(3, 124, 1, sysdate(), 1, 1);

INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(4, 144, 1, sysdate(), 1, 1);

INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(5, 13, 2, sysdate(), 2, 1);

INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(6, 13, 2, sysdate(), 2, 1);

INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(7, 122, 2, sysdate(), 1, 2);

INSERT INTO EXAMEN (IDE_SOLICITUD_EXAMEN, COD_EXAMEN, IDE_PERSONAL_MED, FEC_EXAMEN, ID_INTERNACION, IDE_EXPEDIENTE )
VALUES(8, 122, 1, sysdate(), 1, 2);